### ISSUE TITLE
MapEntry doesn't render the map

### ISSUE THREAD

**Issue by gustavocaiano** [dotswan/filament-map-picker#70]
Hi , before anything thank you for the package!

I am unable to render the map in the view page's InfoList:

![Image](https://github.com/user-attachments/assets/7fc7e6fe-8174-4f6b-8981-3f76ae60c9fd)

There is no problem with Map Field in the form as it saves lat and lng well.
I followed the instructions in the README so, if the problem can't be reproduced I would appreciate some help to knopw what is going on.

my code (simplified):

```
 MapEntry::make('location')
                ->state(fn ($record) => ['lat' => $record?->latitude, 'lng' => $record?->longitude])
               ->draggable(false)
               ->tilesUrl('https://tile.openstreetmap.org/{z}/{x}/{y}.png'),
```
I also tried without -state() as i have the Attribute: 
```
    protected function location(): Attribute
    {
        return Attribute::make(
            get: fn (mixed $value, array $attributes) => [ 
                'latitude' => $attributes['latitude'],
                'longitude' => $attributes['longitude'],
            ],
            set: fn (array $value) => [
                'latitude' => $value['lat'],
                'longitude' => $value['lng'],
            ],
        );
    }
```

Thank you for your help

**Comment by mohaphez** [comment]
Hi @gustavocaiano 

The issue seems to be with rendering the tiles.  
The map itself has been rendered correctly, and there are no errors.  

In the console log, under the network section, do you encounter any errors while rendering the map tile images?  

Perhaps you're getting a CORS error if you're using a local domain without HTTPS, such as `example.test`.  

You might want to test with a different `tileUrl` to see if it works, for example:  
`https://mts0.google.com/vt/lyrs=y&hl=es&x={x}&y={y}&z={z}`  

Have you tried zooming in and out on the map?  

Do you see any errors in the console?

**Comment by gustavocaiano** [comment]
![Image](https://github.com/user-attachments/assets/20c04ab2-bf06-405d-9bdd-91e1c425286c)
this is my console errors.

I am a bit confused as why I don't get these erros in the Form and it works perfectly, but i do in the view page. 

Nothing changes when zooming in and out.

How can i trace the cause of error ? 

Also sorry if Im not doing something that i should as it is my first time using a package like this. do i need additional setup im my application?

im currently running locally accessing via localhost so i dont think it is a CORS Error

**Comment by gustavocaiano** [comment]
Also maybe it helps mentioning that i tried using the form view in the infolist and it rendered without any problem (some other erros related to state and value but the tiles were there)

**Comment by yeganehha** [comment]
Hi @gustavocaiano 

I am using version v1.7.1 and in this version I fixed the problem by following the steps below.

1. Publish view files of package:
`php artisan vendor:publish --provider="Dotswan\MapPicker\MapPickerServiceProvider" `--tag="views"``

2. Inside `resources/views/vendor/map-picker/infolists/osm-map-entry.blade.php` add bellow line inside main Div:
`<input type="text" id="{{ $getId() }}_fmrest" style="display:none"/>`

The final file should look like the following code:
`
<x-dynamic-component :component="$getEntryWrapperView()" :entry="$entry">

    <div x-data="mapPicker($wire, {{ $getMapConfig() }}, @js($getState()))"
        x-init="async () => {
            do {
                await (new Promise(resolve => setTimeout(resolve, 100)));
        } while (!$refs.map);
        attach($refs.map);
    }" wire:ignore>
        <div x-ref="map" class="w-full" style="min-height: 30vh; z-index: 1 !important; {{ $getExtraStyle() }}">
        </div>
        <input type="text" id="{{ $getId() }}_fmrest" style="display:none"/>
    </div>

</x-dynamic-component>

`

**Comment by gustavocaiano** [comment]
hi @yeganehha 
Thank you for your response.
The map showed up after that change, but the marker is always at lat:0 lng:0. im having problems hydrating the state.
I get this in Console: 

<img width="659" alt="Image" src="https://github.com/user-attachments/assets/ceb971c8-6c48-49bc-85b6-c0a09a4c433c" />

also after those changes you recommended i got this in console: 

<img width="1493" alt="Image" src="https://github.com/user-attachments/assets/3e09569f-4ae1-4a50-85c2-f4bdd539da3f" />

Did this happen to you? 
Could you share how you set up the field?
(sorry for the error dump here)

**Comment by yeganehha** [comment]
Hi @gustavocaiano 
I post my code here, I hope this helps.

In Resource:
```
 MapEntry::make('location')
                        ->columnSpan(2)
                        ->extraStyles([
                            'min-height: 300px',
                            'border-radius: 5px'
                        ])
                        ->state(fn (Attendance $record) => ['lat' => $record->latitude, 'lng' => $record->longitude])
                        ->showMarker()
                        ->markerColor("#22c55eff")
                        ->showFullscreenControl()
                        ->columnSpan(2)
                        ->draggable(false)
                        ->zoom(12)
                        ->tilesUrl("https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"),
```

Inside `resources/views/vendor/map-picker/infolists/osm-map-entry.blade.php`
```
<x-dynamic-component :component="$getEntryWrapperView()" :entry="$entry">

    <div x-data="mapPicker($wire, {{ $getMapConfig() }}, @js($getState()))"
        x-init="async () => {
            do {
                await (new Promise(resolve => setTimeout(resolve, 100)));
        } while (!$refs.map);
        attach($refs.map);
    }" wire:ignore>
        <div x-ref="map" class="w-full" style="min-height: 30vh; z-index: 1 !important; {{ $getExtraStyle() }}">
        </div>
        <input type="text" id="{{ $getId() }}_fmrest" style="display:none"/>
    </div>

</x-dynamic-component>
```

**Comment by gustavocaiano** [comment]
Thank you! 
Im still getting an error but it must be something i did wrong in the model.
(Also, you repeated ->columnSpan(2) in your entry)

**Comment by gustavocaiano** [comment]
Oh... i tested in safari and it works fine, not in Arc... @mohaphez @yeganehha

**Comment by gustavocaiano** [comment]
I figured it out, it was a permission missing in my browser to access location. Thank you!
